# Generated by Django 4.1 on 2023-01-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_abilities_abilityid_effects_abilityid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="inventory",
        ),
        migrations.AddField(
            model_name="inventory",
            name="Items",
            field=models.ManyToManyField(to="inventory.inventoryitem"),
        ),
    ]
